### ISSUE TITLE
If I set custom timeframe error appears

### ISSUE THREAD

**Issue by anikievev** [GeneralMills/pytrends#102]
Try to build_payload with custom timeframe
`pytrend.build_payload(kw_list=['test'], timeframe='now 5-d')`

Result:

```
Traceback (most recent call last):
  File "trends.py", line 11, in <module>
    pytrend.build_payload(kw_list=['test'], timeframe='now 5-d')
  File "/usr/local/lib/python2.7/dist-packages/pytrends/request.py", line 79, in build_payload
    self._tokens(token_payload)
  File "/usr/local/lib/python2.7/dist-packages/pytrends/request.py", line 92, in _tokens
    widget_dict = json.loads(widget_json)['widgets']
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by dreyco676** [comment]
I updated the readme. Unfortunately Google only allows 'now 1-d' or 'now 7-d' for that. You are allowed to specify exact times using begin and end date 'YYYY-MM-DD YYYY-MM-DD'
