### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by bigEvilBanana** [GeneralMills/pytrends#116]
Some problem when I use in kw_list more then one word. 

`pytrend = TrendReq(google_username, google_password, custom_useragent='Chrome')
pytrend.build_payload(kw_list='Apple inc')
interest_over_time_df = pytrend.interest_over_time()
print  interest_over_time_df`

![image](https://cloud.githubusercontent.com/assets/17427666/23405347/d1c55eb8-fdca-11e6-8327-a59119d50fe2.png)

How can I get data from words with spaces?

**Comment by dreyco676** [comment]
That's not a list. ['Apple inc'] is a list.

**Comment by Dayjo** [comment]
@dreyco676 Here's the same result using the actual example.py;

```bash
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    pytrend.build_payload(kw_list=['pizza', 'bagel'])
  File "/Library/Python/2.7/site-packages/pytrends/request.py", line 81, in build_payload
    self._tokens(token_payload)
  File "/Library/Python/2.7/site-packages/pytrends/request.py", line 94, in _tokens
    widget_dict = json.loads(widget_json)['widgets']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by bigEvilBanana** [comment]
Thanks, dreyco676. I've solved this problem. Actually when I used foreach through the list with kw, I sent to the build_payload() item of list, but not the list of items (e.g. kw=[item])
