### ISSUE TITLE
running example

### ISSUE THREAD

**Issue by ALIrezanouri** [GeneralMills/pytrends#143]
hi there , me be stupid by i am new to programming
I tried to run example with my cereds , but i got some errors , can somebody say what should i do step by steps ? thanx in advanced 

this is the error :
Traceback (most recent call last):
  File "C:/Users/alireza/PycharmProjects/untitled11/examples/example.py", line 1, in <module>
    from pytrends.request import TrendReq
  File "C:\Users\alireza\PycharmProjects\untitled11\pytrends\request.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by ALIrezanouri** [comment]
fixed my issues 👍
