### ISSUE TITLE
ValueError: year is out of range

### ISSUE THREAD

**Issue by CedYF** [GeneralMills/pytrends#182]
I'm trying to install and run pytrends, but every time I hit this bug: "ValueError: year is out of range"

I'm not sure if it's just the version of python I'm using. Any clarification would be appreciated. 

``Traceback (most recent call last):
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/pandas/tseries/tools.py", line 380, in _convert_listlike
    values, tz = tslib.datetime_to_datetime64(arg)
  File "pandas/tslib.pyx", line 1474, in pandas.tslib.datetime_to_datetime64 (pandas/tslib.c:27342)
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trends.py", line 15, in <module>
    print(pytrend.interest_over_time())
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/pytrends/request.py", line 164, in interest_over_time
    df['date'] = pd.to_datetime(df['time'], unit='s')
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/pandas/util/decorators.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/pandas/tseries/tools.py", line 276, in to_datetime
    unit=unit, infer_datetime_format=infer_datetime_format)
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/pandas/tseries/tools.py", line 390, in _to_datetime
    values = _convert_listlike(arg._values, False, format)
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/pandas/tseries/tools.py", line 383, in _convert_listlike
    raise e
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/pandas/tseries/tools.py", line 372, in _convert_listlike
    require_iso8601=require_iso8601)
  File "pandas/tslib.pyx", line 1847, in pandas.tslib.array_to_datetime (pandas/tslib.c:37155)
  File "pandas/tslib.pyx", line 2036, in pandas.tslib.array_to_datetime (pandas/tslib.c:36750)
  File "pandas/tslib.pyx", line 2030, in pandas.tslib.array_to_datetime (pandas/tslib.c:36640)
  File "pandas/tslib.pyx", line 1619, in pandas.tslib.parse_datetime_string (pandas/tslib.c:29385)
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/dateutil/parser.py", line 1008, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/Ced/anaconda/lib/python3.5/site-packages/dateutil/parser.py", line 404, in parse
    ret = default.replace(**repl)
ValueError: year is out of range``

**Comment by CedYF** [comment]
If this happens you then just do this:
pip install --upgrade pandas

I was using an out of date version of panda.
