### ISSUE TITLE
KeyError: "['geoName' 'value'] not in index"

### ISSUE THREAD

**Issue by nxfxcom** [GeneralMills/pytrends#189]
Hello,

when I am running the following:
`
pytrend = TrendReq()
pytrend.build_payload(kw_list=['New Midsize Cars','New Electric Cars','New Hybrid Cars','New Super Cars','New Cheap Cars'],geo="US")
interest_by_region_df = pytrend.interest_by_region()
print(interest_by_region_df)
`

I get:
`Traceback (most recent call last):
  File "/Users/myuser/PycharmProjects/Trends_Final/step1.py", line 14, in <module>
    interest_by_region_df = pytrend.interest_by_region()
  File "/Users/myuser/anaconda/lib/python3.5/site-packages/pytrends/request.py", line 208, in interest_by_region
    df = df[['geoName', 'value']].set_index(['geoName']).sort_index()
  File "/Users/myuser/anaconda/lib/python3.5/site-packages/pandas/core/frame.py", line 1991, in __getitem__
    return self._getitem_array(key)
  File "/Users/myuser/anaconda/lib/python3.5/site-packages/pandas/core/frame.py", line 2035, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/Users/myuser/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py", line 1214, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['geoName' 'value'] not in index"
`

I assume it might be because of low values, but I am not sure. Any advice?

Thank you

**Comment by jtcasal** [comment]
This should be fixed now. I submitted a PR and it is already merged. It will return an empty dataframe when google has no trend data.

**Comment by dreyco676** [comment]
@jtcasal thanks for the PR!
