### ISSUE TITLE
Year Is Out Of Range

### ISSUE THREAD

**Issue by mocomber** [GeneralMills/pytrends#205]
When running the test code, I get the following error:

Traceback (most recent call last):
  File "alt_monitor.py", line 49, in <module>
    checkTrends()
  File "alt_monitor.py", line 42, in checkTrends
    interest_over_time_df = pytrend.interest_over_time()
  File "//anaconda/lib/python2.7/site-packages/pytrends/request.py", line 164, in interest_over_time
    df['date'] = pd.to_datetime(df['time'], unit='s')
  File "//anaconda/lib/python2.7/site-packages/pandas/util/decorators.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/pandas/tseries/tools.py", line 276, in to_datetime
    unit=unit, infer_datetime_format=infer_datetime_format)
  File "//anaconda/lib/python2.7/site-packages/pandas/tseries/tools.py", line 390, in _to_datetime
    values = _convert_listlike(arg._values, False, format)
  File "//anaconda/lib/python2.7/site-packages/pandas/tseries/tools.py", line 383, in _convert_listlike
    raise e
ValueError: year is out of range

I've tried adding different timeframe values, leaving it out, nothing seems to get past this one.

**Comment by mocomber** [comment]
My search was only showing open tickets - need to update panads.
