### ISSUE TITLE
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.

### ISSUE THREAD

**Issue by samuruga** [GeneralMills/pytrends#301]
Code :
from pytrends.request import TrendReq
pytrends = TrendReq(hl='en-US', tz=360)
kw_list = ["blockchain"]
pytrends.build_payload(kw_list, cat='finance', timeframe='today 5-y', geo='US', gprop='')
interest_over_time_df = pytrends.interest_over_time()
print(interest_over_time_df.head())

Error 👍 
Traceback (most recent call last):
  File "C:/Users/Hi/Desktop/check.py", line 4, in <module>
    pytrends.build_payload(kw_list, cat='finance', timeframe='today 5-y', geo='US', gprop='')
  File "C:\Users\Hi\AppData\Local\Programs\Python\Python37\lib\site-packages\pytrends\request.py", line 120, in build_payload
    self._tokens()
  File "C:\Users\Hi\AppData\Local\Programs\Python\Python37\lib\site-packages\pytrends\request.py", line 131, in _tokens
    trim_chars=4,
  File "C:\Users\Hi\AppData\Local\Programs\Python\Python37\lib\site-packages\pytrends\request.py", line 101, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.

Can someone help me with this issue, i want the category to be selected as Finance

**Comment by samuruga** [comment]
Found the value for finance which is 7 in category
