### ISSUE TITLE
What should I do if Connection to trends.google.com timed out？

### ISSUE THREAD

**Issue by huangzhaor** [GeneralMills/pytrends#369]
C:\ProgramData\Anaconda3\python.exe C:/Users/Administrator/Desktop/pytrends-master/examples/example.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x0000022ADE7585C0>, 'Connection to trends.google.com timed out. (connect timeout=2)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000022ADE7585C0>, 'Connection to trends.google.com timed out. (connect timeout=2)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/pytrends-master/examples/example.py", line 4, in <module>
    pytrend = TrendReq()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pytrends\request.py", line 58, in __init__
    self.cookies = self.GetGoogleCookie()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pytrends\request.py", line 81, in GetGoogleCookie
    proxies=proxy
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000022ADE7585C0>, 'Connection to trends.google.com timed out. (connect timeout=2)'))

Process finished with exit code 1

**Comment by aspiringguru** [comment]
not sure what code you were running. I was trying the most basic demo. spent a few too many hours trying to datascrape google trends using selenium only to discover google have a robust anti scraping tool.   then I found this package. then your question above as your error message is similar.

but I have no idea what code you were running :(

from pytrends.request import TrendReq
pytrends = TrendReq(hl='en-US', tz=360)
kw_list=['covid', 'covid-19', 'coronavirus']
pytrends.get_historical_interest(kw_list, year_start=2020, month_start=1, day_start=1, hour_start=0, year_end=2020, month_end=4, day_end=2, hour_end=0, cat=0, geo='', gprop='', sleep=0)


HTTPSConnectionPool(host='trends.google.com', port=443): Read timed out. (read timeout=5)

not sure what the error means as I got a dataframe to match the expected number of rows.

**Comment by dsgerbc** [comment]
The simple reason for the error is that the pytrends code does not bother with try/except constructs at all. It only throws a google error is the results.status!=200. Throw some try/except on any instance of _get_data, tokens(),getgooglecookie() and anything requests.*  and you can manage those timeout errors. I may do a pull request if I have the time.

**Comment by SkyStreet** [comment]
Same issue. I suppose something to do with use of VPN to access Google.

**Comment by eduardoleitekf** [comment]
I'm having the same problem while using VPN:

`ConnectTimeout: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /?geo=US (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000022ADE7585C0>, 'Connection to trends.google.com timed out. (connect timeout=2)'))`

Would you know how we could handle this error and be able to get data from Google Trends?
Thanks!

**Comment by dsgerbc** [comment]
Do you have try/except in your pytrends interactions? If yes and those aren't catching this timeout try:
1) Zeroing out pytrends retries/timeout options. I think there's something going on with those in the urllib3 library while using VPN.
2) If that doesn't help, try the changes I suggested in the pull request referenced above. I think there's something weird in urllib3 library's error handling. I do not understand what it is, but adding try/except structure on any interaction with the requests library in the pytrends' request.py code allowed me to catch those timeouts. My scraping code can now run for days unattended.

If you did not have the try/except structure in your main code, try it, and maybe you'd be able to handle those timeouts out of the box.

**Comment by HariprasadManimozhi** [comment]
> 
> 
> Do you have try/except in your pytrends interactions? If yes and those aren't catching this timeout try:
> 
>     1. Zeroing out pytrends retries/timeout options. I think there's something going on with those in the urllib3 library while using VPN.
> 
>     2. If that doesn't help, try the changes I suggested in the pull request referenced above. I think there's something weird in urllib3 library's error handling. I do not understand what it is, but adding try/except structure on any interaction with the requests library in the pytrends' request.py code allowed me to catch those timeouts. My scraping code can now run for days unattended.
> 
> 
> If you did not have the try/except structure in your main code, try it, and maybe you'd be able to handle those timeouts out of the box.

@dsgerbc  Can you please share how you used try/except with pytrend request with code? It could be helpful....

**Comment by dsgerbc** [comment]
It's in the pull request #411 linked above.
https://github.com/GeneralMills/pytrends/pull/411/commits/2ae4ccc67547768cf9b9160f5126369b190264ab

**Comment by HariprasadManimozhi** [comment]
> 
> 
> It's in the pull request #411 linked above.
> [2ae4ccc](https://github.com/GeneralMills/pytrends/commit/2ae4ccc67547768cf9b9160f5126369b190264ab)

It puzzles me. Can you please mention the snippet below, it could be helpful. TIA.

**Comment by suad-b** [comment]
Thank you @dsgerbc !!
@HariprasadManimozhi I had the same issue this morning, here's a screenshot of how I solved it.

![Annotation 2020-08-19 170558](https://user-images.githubusercontent.com/69911565/90652354-46afd680-e23e-11ea-87e0-cc8a1fd80cbe.png)

**Comment by HariprasadManimozhi** [comment]
> 
> 
> Thank you @dsgerbc !!
> @HariprasadManimozhi I had the same issue this morning, here's a screenshot of how I solved it.
> 
> ![Annotation 2020-08-19 170558](https://user-images.githubusercontent.com/69911565/90652354-46afd680-e23e-11ea-87e0-cc8a1fd80cbe.png)

Thanks for the reply

**Comment by ousooners2834** [comment]
> > Thank you @dsgerbc !!
> > @HariprasadManimozhi I had the same issue this morning, here's a screenshot of how I solved it.
> > ![Annotation 2020-08-19 170558](https://user-images.githubusercontent.com/69911565/90652354-46afd680-e23e-11ea-87e0-cc8a1fd80cbe.png)
> 
> Thanks for the reply

This worked for me. Thank you for posting.

**Comment by igmendozac** [comment]
> > > Thank you @dsgerbc !!
> > > @HariprasadManimozhi I had the same issue this morning, here's a screenshot of how I solved it.
> > > ![Annotation 2020-08-19 170558](https://user-images.githubusercontent.com/69911565/90652354-46afd680-e23e-11ea-87e0-cc8a1fd80cbe.png)
> > 
> > 
> > Thanks for the reply
> 
> This worked for me. Thank you for posting.

Guys! What is single_names? in your code?

**Comment by suad-b** [comment]
> > > > Thank you @dsgerbc !!
> > > > @HariprasadManimozhi I had the same issue this morning, here's a screenshot of how I solved it.
> > > > ![Annotation 2020-08-19 170558](https://user-images.githubusercontent.com/69911565/90652354-46afd680-e23e-11ea-87e0-cc8a1fd80cbe.png)
> > > 
> > > 
> > > Thanks for the reply
> > 
> > 
> > This worked for me. Thank you for posting.
> 
> Guys! What is single_names? in your code?

In my code I had a list with the exact Keywords from Google Trends. Ex. one of the values on the list is "/m/03m66l" which stands for A+ Programming language.

**Comment by saraafernandeez** [comment]
Adding the _requests_args={'verify':False}_ parameter doesn't give an error (is ignores SSL errors, because the server and browser cannot establish a secure connection).

_pytrends = TrendReq(requests_args={'verify':False})_

**Comment by davins90** [comment]
> 

Great solution! Thanks!
