### ISSUE TITLE
Initialization fails

### ISSUE THREAD

**Issue by MoritzStefaner** [GeneralMills/pytrends#41]
Hi,

I am getting the following errors as of recently

```
Traceback (most recent call last):
  File "..", line 32, in <module>
    connector = pyGTrends(google_username, google_password)
  File "/Library/Python/2.7/site-packages/pytrends/pyGTrends.py", line 41, in __init__
    self.fake_ua = UserAgent()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 10, in __init__
    self.data = load_cached()
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 140, in load_cached
    update()
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 135, in update
    write(load())
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 92, in load
    browsers_dict[browser_key] = get_browser_versions(browser)
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 55, in get_browser_versions
    html = html.split('<div id=\'liste\'>')[1]
IndexError: list index out of range
```

The same code worked fine a few days ago. Has Google maybe changed their HTML code? Any tips?

**Comment by AndersOLDahl** [comment]
Seeing the same issue. Worked last night for me.

**Comment by dreyco676** [comment]
Hmm I probably won't get to this until next week but it looks like fake_useragent might have changed. Did you update that recently?

**Comment by AndersOLDahl** [comment]
Works now after updating fake_useragent 👍

**Comment by dreyco676** [comment]
Cool, what is the current version and I can require that.

**Comment by MoritzStefaner** [comment]
Can confirm it works with fake-useragent-0.1.0. Great!
