### ISSUE TITLE
Script throws error if Google Trends returns no data

### ISSUE THREAD

**Issue by cdshinde** [GeneralMills/pytrends#67]
If we use a keyword q="Tied tee shirt dress". Google Trends will not return any data, due to less amount of data.
The python script gives this error:
Python Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pytrends/request.py", line 79, in trend
    self.results = json.loads(text)
  File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "individual.py", line 18, in <module>
    df = pytrend.trend(trend_payload, return_type='dataframe')
  File "/usr/local/lib/python3.4/dist-packages/pytrends/request.py", line 81, in trend
    raise ResponseError(req.content)
  File "/usr/local/lib/python3.4/dist-packages/pytrends/request.py", line 200, in **init**
    self.server_error = BeautifulSoup(content, "lxml").findAll("div", {"class": "errorSubTitle"})[0].get_text()
IndexError: list index out of range
Could you fix this so that it goes returns 0.

**Comment by AndersOLDahl** [comment]
Been seeing this error today as well. It helped me with debugging. Should an error be thrown if no data gets sent back? Both approaches are valid, I think. Either way, the error should at least be more descriptive.

**Comment by dreyco676** [comment]
I will put this on the TODO list. I think the best way to handle it is to throw an error that is more descriptive like NoResultsError which then you can handle however you'd like rather than mangling the data. The potential problem I see with hardcoding 0 is what if the service is just down?
