### ISSUE TITLE
Fails to connect to Google

### ISSUE THREAD

**Issue by cfenollosa** [GeneralMills/pytrends#74]
Hi,

I'm trying to run an example and pytrends drops an error in the `_connect()` method. It seems that maybe it's trying to find the wrong DOM element?

(Note: the log includes Flask's trace because I'm using this in a web app)

```
[2016-10-26 19:17:22,557] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "env/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "env/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "env/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "env/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "env/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cfenollosa/Dropbox/Documents/Code/python/afm_prototype/afm_prototype.py", line 26, in index
    custom_useragent=user_agent)
  File "env/lib/python2.7/site-packages/pytrends/request.py", line 34, in __init__
    self._connect()
  File "env/lib/python2.7/site-packages/pytrends/request.py", line 49, in _connect
    dico[u['name']] = u['value']
  File "env/lib/python2.7/site-packages/bs4/element.py", line 997, in __getitem__
    return self.attrs[key]
KeyError: u'name'
```

**Comment by cfenollosa** [comment]
Furthermore, why is Google login necessary? It works as well without auth, and [this Node.js library](https://github.com/pat310/google-trends-api) works without auth. Is there a strong reason?

**Comment by dreyco676** [comment]
You will notice that it will limit the number of requests without it.
Unfortunately there is a bug in which the logged in session does not get
passed to the request so it nets out to the same 20 requests/hr as not
logging in.

On Wed, Oct 26, 2016 at 12:47 PM, Carlos Fenollosa <notifications@github.com

**Comment by cfenollosa** [comment]
Alright, so then we should discover why the auth fails.

I think that Google recently changed their login window, and instead of entering username + password on the same page, users are now required to input username, click "send", then enter password. May that be the source of the problem?

**Comment by dreyco676** [comment]
I'd love it if we could figure that out. I won't be able to really dig in
until the second week of December.

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
