### ISSUE TITLE
trend payload doesn't work with alternate ID

### ISSUE THREAD

**Issue by raspbp** [GeneralMills/pytrends#95]
when I try to run 

`trend_payload = {'q': '%2Fm%2F04sv4'}
trend = pytrend.trend(trend_payload, return_type='dataframe')
print(trend)`

I get the following error

`Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pytrends/request.py", line 79, in trend
    self.results = json.loads(text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/MS/GTD.py", line 21, in <module>
    trend = pytrend.trend(trend_payload, return_type='dataframe')
  File "/usr/local/lib/python3.4/dist-packages/pytrends/request.py", line 81, in trend
    raise ResponseError(req.content)
  File "/usr/local/lib/python3.4/dist-packages/pytrends/request.py", line 200, in __init__
    self.server_error = BeautifulSoup(content, "lxml").findAll("div", {"class": "errorSubTitle"})[0].get_text()
IndexError: list index out of range`

If I use a keyword I get intended results but topic codes seem to all produce the same error

**Comment by nysthee** [comment]
The error you get is the same I get when no data is available for a given term.

**Comment by dreyco676** [comment]
New version released, let me know if this is a continued issue by reopening.
